export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const GET_USER_BEGINS = 'GET_USER_BEGINS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
export const SIGN_UP = 'SIGN_UP';

export const GET_PROJECTS_BEGINS = 'GET_PROJECTS_BEGINS';
export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECT_USERS_BEGINS = 'GET_PROJECT_USERS_BEGINS';
export const GET_PROJECT_USERS_SUCCESS = 'GET_PROJECT_USERS_SUCCESS';
export const GET_PROJECT_USERS_FAILURE = 'GET_PROJECT_USERS_FAILURE';
export const ADD_PROJECT_BEGINS = 'ADD_PROJECT_BEGINS';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_FAILURE = 'ADD_PROJECT_FAILURE';
export const UPDATE_PROJECT_BEGINS = 'UPDATE_PROJECT_BEGINS';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE';
export const UPDATE_PROJECT_MODELS_BEGINS = 'UPDATE_PROJECT_MODELS_BEGINS';
export const UPDATE_PROJECT_MODELS_SUCCESS = 'UPDATE_PROJECT_MODELS_SUCCESS';
export const UPDATE_PROJECT_MODELS_FAILURE = 'UPDATE_PROJECT_MODELS_FAILURE';
export const DELETE_PROJECT_BEGINS = 'DELETE_PROJECT_BEGINS';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';


export const UPLOAD_MODEL_BEGINS = 'UPLOAD_MODEL_BEGINS';
export const UPLOAD_MODEL_SUCCESS = 'UPLOAD_MODEL_SUCCESS';
export const UPLOAD_MODEL_FAILURE = 'UPLOAD_MODEL_FAILURE';
export const DOWNLOAD_MODEL_BEGINS = 'DOWNLOAD_MODEL_BEGINS';
export const DOWNLOAD_MODEL_SUCCESS = 'DOWNLOAD_MODEL_SUCCESS';
export const DOWNLOAD_MODEL_FAILURE = 'DOWNLOAD_MODEL_FAILURE';
export const UPLOAD_MODEL_DATA_BEGINS = 'UPLOAD_MODEL_DATA_BEGINS';
export const UPLOAD_MODEL_DATA_SUCCESS = 'UPLOAD_MODEL_DATA_SUCCESS';
export const UPLOAD_MODEL_DATA_FAILURE = 'UPLOAD_MODEL_DATA_FAILURE';
export const DOWNLOAD_MODEL_DATA_BEGINS = 'DOWNLOAD_MODEL_DATA_BEGINS';
export const DOWNLOAD_MODEL_DATA_SUCCESS = 'DOWNLOAD_MODEL_DATA_SUCCESS';
export const DOWNLOAD_MODEL_DATA_FAILURE = 'DOWNLOAD_MODEL_DATA_FAILURE';



export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const GET_ACCESS_TOKEN_FAILURE = 'GET_ACCESS_TOKEN_FAILURE';
export const GET_ASSET_DATA = 'GET_ASSET_DATA';
export const GET_ASSET_DATA_FAILS = 'GET_ASSET_DATA_FAILS';
export const UPDATE_ASSET_DATA_BEGINS = 'UPDATE_ASSET_DATA_BEGINS';
export const UPDATE_ASSET_DATA_SUCCESS = 'UPDATE_ASSET_DATA_SUCCESS';
export const UPDATE_ASSET_DATA_FAILS = 'UPDATE_ASSET_DATA_FAILS';


export const GET_ASSET_CATEGORY_BEGINS = 'GET_ASSET_CATEGORY_BEGINS';
export const GET_ASSET_CATEGORY_SUCCESS = 'GET_ASSET_CATEGORY_SUCCESS';
export const GET_ASSET_CATEGORY_FAILURE = 'GET_ASSET_CATEGORY_FAILURE';
export const ADD_ASSET_CATEGORY_BEGINS = 'ADD_ASSET_CATEGORY_BEGINS';
export const ADD_ASSET_CATEGORY_SUCCESS = 'ADD_ASSET_CATEGORY_SUCCESS';
export const ADD_ASSET_CATEGORY_FAILURE = 'ADD_ASSET_CATEGORY_FAILURE';
export const UPDATE_ASSET_CATEGORY_BEGINS = 'UPDATE_ASSET_CATEGORY_BEGINS';
export const UPDATE_ASSET_CATEGORY_SUCCESS = 'UPDATE_ASSET_CATEGORY_SUCCESS';
export const UPDATE_ASSET_CATEGORY_FAILURE = 'UPDATE_ASSET_CATEGORY_FAILURE';
export const DELETE_ASSET_CATEGORY_BEGINS = 'DELETE_ASSET_CATEGORY_BEGINS';
export const DELETE_ASSET_CATEGORY_SUCCESS = 'DELETE_ASSET_CATEGORY_SUCCESS';
export const DELETE_ASSET_CATEGORY_FAILURE = 'DELETE_ASSET_CATEGORY_FAILURE';
export const GET_ASSET_FIELDS_BEGINS = 'GET_ASSET_FIELDS_BEGINS';
export const GET_ASSET_FIELDS_SUCCESS = 'GET_ASSET_FIELDS_SUCCESS';
export const GET_ASSET_FIELDS_FAILURE = 'GET_ASSET_FIELDS_FAILURE';
export const ADD_ASSET_FIELDS_BEGINS = 'ADD_ASSET_FIELDS_BEGINS';
export const ADD_ASSET_FIELDS_SUCCESS = 'ADD_ASSET_FIELDS_SUCCESS';
export const ADD_ASSET_FIELDS_FAILURE = 'ADD_ASSET_FIELDS_FAILURE';
export const UPDATE_ASSET_FIELDS_BEGINS = 'UPDATE_ASSET_FIELDS_BEGINS';
export const UPDATE_ASSET_FIELDS_SUCCESS = 'UPDATE_ASSET_FIELDS_SUCCESS';
export const UPDATE_ASSET_FIELDS_FAILURE = 'UPDATE_ASSET_FIELDS_FAILURE';
export const DELETE_ASSET_FIELDS_BEGINS = 'DELETE_ASSET_FIELDS_BEGINS';
export const DELETE_ASSET_FIELDS_SUCCESS = 'DELETE_ASSET_FIELDS_SUCCESS';
export const DELETE_ASSET_FIELDS_FAILURE = 'DELETE_ASSET_FIELDS_FAILURE';

export const GET_USERS_BEGINS = 'GET_USERS_BEGINS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';
export const UPDATE_USER_BEGINS = 'UPDATE_USER_BEGINS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const UPDATE_USER_PROFILE_BEGINS = 'UPDATE_USER_PROFILE_BEGINS';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE';
export const DELETE_USER_BEGINS = 'DELETE_USER_BEGINS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';
export const INVITE_USER_BEGINS = 'INVITE_USER_BEGINS';
export const INVITE_USER_SUCCESS = 'INVITE_USER_SUCCESS';
export const INVITE_USER_FAILURE = 'INVITE_USER_FAILURE';
export const REMOVE_USER_BEGINS = 'REMOVE_USER_BEGINS';
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';
export const REMOVE_USER_FAILURE = 'REMOVE_USER_FAILURE';

export const CHANGE_PASSWORD_BEGINS = 'CHANGE_PASSWORD_BEGINS';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';
export const FORGOT_PASSWORD_BEGINS = 'FORGOT_PASSWORD_BEGINS';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
export const RESET_PASSWORD_BEGINS = 'RESET_PASSWORD_BEGINS';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
